# Generated by Django 3.2.18 on 2023-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beautyprof', '0002_auto_20230411_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='add about your work and contact', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
