# Generated by Django 3.2.18 on 2023-04-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyprof', '0004_alter_profile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='name',
        ),
    ]
