# Generated by Django 3.2.18 on 2023-04-16 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyprof', '0006_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
