# Generated by Django 3.2.18 on 2023-04-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beautyprof', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
